name: Question
description: Ask a question about using the Image Editor
title: "[Question]: "
labels: ["question", "needs-response"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! 💬
        
        Please check the documentation and existing discussions before asking a new question.

  - type: dropdown
    id: question-type
    attributes:
      label: Question Type
      description: What type of question do you have?
      options:
        - Installation/Setup
        - Usage/How-to
        - Configuration
        - Performance
        - Compatibility
        - Development/Contributing
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: "How do I..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context about what you're trying to accomplish.
      placeholder: "I'm trying to..."

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Image Editor are you using?
      placeholder: "e.g., 2.0.0"

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 11
        - Windows 10
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Ubuntu Linux
        - Other Linux
        - Other
        - Not applicable

  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: What have you already tried to solve this problem?
      placeholder: "I have tried..."

  - type: checkboxes
    id: resources
    attributes:
      label: Documentation Check
      description: Have you checked these resources?
      options:
        - label: I have read the README.md
        - label: I have checked the documentation
        - label: I have searched existing issues and discussions
        - label: I have checked the CONTRIBUTING.md (for development questions)
